# Autogenerated wrapper script for rmapi_jll for i686-w64-mingw32
export rmapi

JLLWrappers.@generate_wrapper_header("rmapi")
JLLWrappers.@declare_executable_product(rmapi)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        rmapi,
        "bin\\rmapi.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
